/* Vyasa Guru - backend core (Gemini) */
"use strict";
const KB = require("../../chatbot/chatbot-kb.js");
const { GoogleGenAI } = require("@google/genai");
const MAX_MESSAGE_LENGTH=2000; const MAX_HISTORY=20; const MAX_REQUESTS_PER_WINDOW=30; const RATE_WINDOW_MS=10*60*1000; const DEFAULT_TIMEOUT=15000; const DEFAULT_GEMINI_MODEL="gemini-2.5-flash";
const FALLBACK_RATE="Vyasa Guru is taking a short break. Please try again in a moment."; const FALLBACK_NOAPI="I don't have verified information about that yet. Please contact Vyasa Academy for the latest details.";
const buckets=new Map();
function rateLimited(key){const n=Date.now();const a=buckets.get(key)||[];const f=a.filter(t=>n-t<RATE_WINDOW_MS);if(f.length>=MAX_REQUESTS_PER_WINDOW){buckets.set(key,f);return true;}f.push(n);buckets.set(key,f);return false;}
function getConfig(){return{geminiApiKey:process.env.GEMINI_API_KEY||"",geminiModel:process.env.GEMINI_MODEL||DEFAULT_GEMINI_MODEL,timeoutMs:parseInt(process.env.AI_TIMEOUT_MS||String(DEFAULT_TIMEOUT),10)||DEFAULT_TIMEOUT};}
function buildSystemPrompt(p){const facts=KB.FACTS;const ctx=p&&typeof p==="object"?p:{};const l=[];if(ctx.path)l.push("- Current page path: "+ctx.path);if(ctx.title)l.push("- Page title: "+ctx.title);if(ctx.class)l.push("- Class: "+ctx.class);if(ctx.subject)l.push("- Subject: "+ctx.subject);if(ctx.chapter)l.push("- Chapter: "+ctx.chapter);if(ctx.resource)l.push("- Resource context: "+ctx.resource);return["You are Vyasa Guru, the AI learning companion for Vyasa Academy (Hulimavu, Bangalore).","Brand: VYASA ACADEMY - Learn • Understand • Excel.","Help with Mathematics, Science, CBSE study material, Class 6–12 academics, notes, practice papers, quizzes, chapter tests, courses, admissions, academy information.","Be friendly, educational, concise, accurate, encouraging, age-appropriate. Explain step by step, show formulas/calculations clearly when solving maths, encourage understanding.","Only use verified facts about Vyasa Academy. Never invent fees, discounts, student numbers, results, pass percentages, rankings, awards, reviews, faculty credentials, guarantees, course claims, or admission promises.","If academy information is not verified/available, respond exactly: \"I don't have verified information about that yet. Please contact Vyasa Academy for the latest details.\"","VERIFIED ACADEMY FACTS:","- Name: "+facts.name,"- Tagline: "+facts.tagline,"- Location: "+facts.location,"- Phone/WhatsApp: "+facts.phone+" ("+facts.whatsappLink+")","- Email: "+facts.email,"- Classes: "+facts.classes,"- Curriculum: "+facts.boards,"- Subjects: "+facts.subjects,"- Areas served: "+facts.areasServed.join(", "),(l.length?["CURRENT PAGE CONTEXT:",...l]:[]),"STUDY MATERIAL RULES:","- Hub: "+KB.LINKS.sm,"- Class 10 Maths: "+KB.LINKS.maths,"- Class 10 Science: "+KB.LINKS.science,"Only link to existing routes; never invent URLs."].flat().join("\n");}
function validateMessages(r){const o=[];if(!Array.isArray(r))throw new Error("bad");const t=r.slice(-MAX_HISTORY);for(const m of t){if(!m||typeof m!=="object")continue;const role=m.role==="assistant"?"assistant":"user";const c=String(m.content||"").slice(0,MAX_MESSAGE_LENGTH);if(c.trim())o.push({role,content:c.trim()});}return o;}
const kbT=new Map();
function fallbackReply(u,s){let st={topic:null};if(s&&kbT.has(s))st={topic:kbT.get(s)};const h=KB.answer(u,st);if(h&&h.text){if(s)kbT.set(s,h.topic||st.topic);return h.text;}return FALLBACK_NOAPI;}
async function callGemini(ms,p,c){const ai=new GoogleGenAI({apiKey:c.geminiApiKey});const sys=buildSystemPrompt(p);const cnt=[];for(const m of ms)cnt.push({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]});const resp=await ai.models.generateContent({model:c.geminiModel,config:{systemInstruction:sys},contents:cnt});const txt=resp?.text||resp?.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("")||"";if(!String(txt).trim())throw new Error("empty");return String(txt).trim();}
async function handleChat(b,m){const c=getConfig();let ms;try{ms=validateMessages(b&&b.messages);}catch(e){return{status:400,body:{success:false,message:"Sorry, I could not understand that request."}};}if(!ms.length)return{status:400,body:{success:false,message:"Sorry, I could not understand that request."}};const s=(b&&typeof b.sessionId==="string")?b.sessionId.slice(0,64):(m&&m.ip)||"anon";if(rateLimited(s))return{status:429,body:{success:false,message:FALLBACK_RATE}};const pc=b&&b.pageContext?b.pageContext:null;if(!c.geminiApiKey){const ut=ms[ms.length-1].content;return{status:200,body:{success:true,message:fallbackReply(ut,s),source:"knowledge"}};}try{const r=await callGemini(ms,pc,c);return{status:200,body:{success:true,message:r,source:"gemini"}};}catch(err){const ut=ms[ms.length-1].content;return{status:200,body:{success:true,message:fallbackReply(ut,s),source:"knowledge"}};}}
function health(){const c=getConfig();return{ok:true,provider:"gemini",model:c.geminiModel,aiConfigured:Boolean(c.geminiApiKey),kbReady:typeof KB.answer==="function"};}
module.exports={handleChat,health,buildSystemPrompt};